package com.sinosoft.gypsymoth.pojo;
// default package

import java.util.Date;


/**
 * AbstractOpLog generated by MyEclipse Persistence Tools
 */

public abstract class AbstractOpLog  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String recordId;
     private String personId;
     private String accountId;
     private String name;
     private String sex;
     private Date birthday;
     private String education;
     private String position;
     private Date passTime;
     private String tel;
     private String mobile;
     private String fax;
     private String email;
     private Integer isCoordinator;
     private Integer isAuthorized;
     private Integer isInspector;
     private String attachment;
     private Date opTime;
     private String opName;
     private String comments;
     private Integer training;
     private String orgId;
     private String personType;
     private String spell;


    // Constructors

    /** default constructor */
    public AbstractOpLog() {
    }

    
    /** full constructor */
    public AbstractOpLog(String recordId, String personId, String accountId, String name, String sex, Date birthday, String education, String position, Date passTime, String tel, String mobile, String fax, String email, Integer isCoordinator, Integer isAuthorized, Integer isInspector, String attachment, Date opTime, String opName, String comments, Integer training, String orgId, String personType,String spell) {
        this.recordId = recordId;
        this.personId = personId;
        this.accountId = accountId;
        this.name = name;
        this.sex = sex;
        this.birthday = birthday;
        this.education = education;
        this.position = position;
        this.passTime = passTime;
        this.tel = tel;
        this.mobile = mobile;
        this.fax = fax;
        this.email = email;
        this.isCoordinator = isCoordinator;
        this.isAuthorized = isAuthorized;
        this.isInspector = isInspector;
        this.attachment = attachment;
        this.opTime = opTime;
        this.opName = opName;
        this.comments = comments;
        this.training = training;
        this.orgId = orgId;
        this.personType = personType;
        this.spell = spell;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    public String getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(String personId) {
        this.personId = personId;
    }

    public String getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getEducation() {
        return this.education;
    }
    
    public void setEducation(String education) {
        this.education = education;
    }

    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }

    public Date getPassTime() {
        return this.passTime;
    }
    
    public void setPassTime(Date passTime) {
        this.passTime = passTime;
    }

    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getIsCoordinator() {
        return this.isCoordinator;
    }
    
    public void setIsCoordinator(Integer isCoordinator) {
        this.isCoordinator = isCoordinator;
    }

    public Integer getIsAuthorized() {
        return this.isAuthorized;
    }
    
    public void setIsAuthorized(Integer isAuthorized) {
        this.isAuthorized = isAuthorized;
    }

    public Integer getIsInspector() {
        return this.isInspector;
    }
    
    public void setIsInspector(Integer isInspector) {
        this.isInspector = isInspector;
    }

    public String getAttachment() {
        return this.attachment;
    }
    
    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }

    public Date getOpTime() {
        return this.opTime;
    }
    
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    public String getOpName() {
        return this.opName;
    }
    
    public void setOpName(String opName) {
        this.opName = opName;
    }

    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    public Integer getTraining() {
        return this.training;
    }
    
    public void setTraining(Integer training) {
        this.training = training;
    }

    public String getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    public String getPersonType() {
        return this.personType;
    }
    
    public void setPersonType(String personType) {
        this.personType = personType;
    }


	public String getSpell() {
		return spell;
	}


	public void setSpell(String spell) {
		this.spell = spell;
	}
   
 







}