package com.sinosoft.gypsymoth.pojo;



/**
 * AbstractProCityPort generated by MyEclipse Persistence Tools
 */

public abstract class AbstractProCityPort  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer proid;
     private Integer cityid;
     private Integer portid;
     private String cityportid;


    // Constructors

    /** default constructor */
    public AbstractProCityPort() {
    }

	/** minimal constructor */
    public AbstractProCityPort(Integer proid, Integer cityid, Integer portid) {
        this.proid = proid;
        this.cityid = cityid;
        this.portid = portid;
    }
    
    /** full constructor */
    public AbstractProCityPort(Integer proid, Integer cityid, Integer portid, String cityportid) {
        this.proid = proid;
        this.cityid = cityid;
        this.portid = portid;
        this.cityportid = cityportid;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProid() {
        return this.proid;
    }
    
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    public Integer getCityid() {
        return this.cityid;
    }
    
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    public Integer getPortid() {
        return this.portid;
    }
    
    public void setPortid(Integer portid) {
        this.portid = portid;
    }

    public String getCityportid() {
        return this.cityportid;
    }
    
    public void setCityportid(String cityportid) {
        this.cityportid = cityportid;
    }
   








}