package com.sinosoft.gypsymoth.pojo;



/**
 * AbstractCity generated by MyEclipse Persistence Tools
 */

public abstract class AbstractCity  implements java.io.Serializable {


    // Fields    

     private String cityname;
     private Promary promary;
     private long cityid;
     private String englishcityname;


    // Constructors

    /** default constructor */
    public AbstractCity() {
    }

	/** minimal constructor */
    public AbstractCity(Promary promary, long cityid) {
        this.promary = promary;
        this.cityid = cityid;
    }
    
    /** full constructor */
    public AbstractCity(Promary promary, long cityid, String englishcityname) {
        this.promary = promary;
        this.cityid = cityid;
        this.englishcityname = englishcityname;
    }

   
    // Property accessors

    public String getCityname() {
        return this.cityname;
    }
    
    public void setCityname(String cityname) {
        this.cityname = cityname;
    }

    public Promary getPromary() {
        return this.promary;
    }
    
    public void setPromary(Promary promary) {
        this.promary = promary;
    }

    public long getCityid() {
        return this.cityid;
    }
    
    public void setCityid(long cityid) {
        this.cityid = cityid;
    }

    public String getEnglishcityname() {
        return this.englishcityname;
    }
    
    public void setEnglishcityname(String englishcityname) {
        this.englishcityname = englishcityname;
    }
   








}