package com.sinosoft.gypsymoth.pojo;

import java.util.Date;

/**
 * AbstractExaminelog generated by MyEclipse Persistence Tools
 */

public abstract class AbstractExaminelog implements java.io.Serializable {

	// Fields    

	private long id;
	private long businessid;
	private String description;
	private String operatorid;
	private Date operatortime;
	private long gypsymoth1;
	private long gypsymoth2;
	private long gypsymoth3;
	private long gypsymoth4;
	private long doubt;
	private String certificate;
	private String examrecord;
	private String workphoto;
	private String gypsymothphoto;
	private String shipinfo;
	private String stopportinfo;
	private String orgId;
	private String orgcode;

	// Constructors

	/** default constructor */
	public AbstractExaminelog() {
	}

	/** full constructor */
	public AbstractExaminelog(long businessid, String description,
			String operatorid, Date operatortime, long gypsymoth1,
			long gypsymoth2, long gypsymoth3, long gypsymoth4, long doubt,
			String certificate, String examrecord, String workphoto,
			String gypsymothphoto,String shipinfo,String stopportinfo,String orgId,String orgcode) {
		this.businessid = businessid;
		this.description = description;
		this.operatorid = operatorid;
		this.operatortime = operatortime;
		this.gypsymoth1 = gypsymoth1;
		this.gypsymoth2 = gypsymoth2;
		this.gypsymoth3 = gypsymoth3;
		this.gypsymoth4 = gypsymoth4;
		this.doubt = doubt;
		this.certificate = certificate;
		this.examrecord = examrecord;
		this.workphoto = workphoto;
		this.gypsymothphoto = gypsymothphoto;
		this.shipinfo=shipinfo;
		this.stopportinfo=stopportinfo;
		this.orgId=orgId;
		this.orgcode=orgcode;
	}

	// Property accessors

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getBusinessid() {
		return this.businessid;
	}

	public void setBusinessid(long businessid) {
		this.businessid = businessid;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getOperatorid() {
		return this.operatorid;
	}

	public void setOperatorid(String operatorid) {
		this.operatorid = operatorid;
	}

	public Date getOperatortime() {
		return this.operatortime;
	}

	public void setOperatortime(Date operatortime) {
		this.operatortime = operatortime;
	}

	public long getGypsymoth1() {
		return this.gypsymoth1;
	}

	public void setGypsymoth1(long gypsymoth1) {
		this.gypsymoth1 = gypsymoth1;
	}

	public long getGypsymoth2() {
		return this.gypsymoth2;
	}

	public void setGypsymoth2(long gypsymoth2) {
		this.gypsymoth2 = gypsymoth2;
	}

	public long getGypsymoth3() {
		return this.gypsymoth3;
	}

	public void setGypsymoth3(long gypsymoth3) {
		this.gypsymoth3 = gypsymoth3;
	}

	public long getGypsymoth4() {
		return this.gypsymoth4;
	}

	public void setGypsymoth4(long gypsymoth4) {
		this.gypsymoth4 = gypsymoth4;
	}

	public long getDoubt() {
		return this.doubt;
	}

	public void setDoubt(long doubt) {
		this.doubt = doubt;
	}

	public String getCertificate() {
		return this.certificate;
	}

	public void setCertificate(String certificate) {
		this.certificate = certificate;
	}

	public String getExamrecord() {
		return this.examrecord;
	}

	public void setExamrecord(String examrecord) {
		this.examrecord = examrecord;
	}

	public String getWorkphoto() {
		return this.workphoto;
	}

	public void setWorkphoto(String workphoto) {
		this.workphoto = workphoto;
	}

	public String getGypsymothphoto() {
		return this.gypsymothphoto;
	}

	public void setGypsymothphoto(String gypsymothphoto) {
		this.gypsymothphoto = gypsymothphoto;
	}

	public String getShipinfo() {
		return shipinfo;
	}

	public void setShipinfo(String shipinfo) {
		this.shipinfo = shipinfo;
	}

	public String getStopportinfo() {
		return stopportinfo;
	}

	public void setStopportinfo(String stopportinfo) {
		this.stopportinfo = stopportinfo;
	}

	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public String getOrgcode() {
		return orgcode;
	}

	public void setOrgcode(String orgcode) {
		this.orgcode = orgcode;
	}
	
}