package com.sinosoft.gypsymoth.pojo;

import java.util.Date;


/**
 * AbstractOrgLog generated by MyEclipse Persistence Tools
 */

public abstract class AbstractOrgLog  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String orgId;
     private String orgSname;
     private String orgFname;
     private String address;
     private String contact;
     private String tel;
     private String fax;
     private String email;
     private Integer proid;
     private String comments;
     private Date opTime;
     private String opPerson;
     private Integer orgStatus;
     private Integer nationid;
     private Integer cityid;
     private String parentId;
     private String bankaccount;
     private String vbrk;


    // Constructors

    /** default constructor */
    public AbstractOrgLog() {
    }

	/** minimal constructor */
    public AbstractOrgLog(String orgId, String orgSname, String orgFname, String address, String contact, String tel, String fax, String email, Date opTime, String opPerson, Integer orgStatus) {
        this.orgId = orgId;
        this.orgSname = orgSname;
        this.orgFname = orgFname;
        this.address = address;
        this.contact = contact;
        this.tel = tel;
        this.fax = fax;
        this.email = email;
        this.opTime = opTime;
        this.opPerson = opPerson;
        this.orgStatus = orgStatus;
    }
    
    /** full constructor */
    public AbstractOrgLog(String orgId, String orgSname, String orgFname, String address, String contact, String tel, String fax, String email, Integer proid, String comments, Date opTime, String opPerson, Integer orgStatus, Integer nationid, Integer cityid, String parentId,String bankaccount,String vbrk) {
        this.orgId = orgId;
        this.orgSname = orgSname;
        this.orgFname = orgFname;
        this.address = address;
        this.contact = contact;
        this.tel = tel;
        this.fax = fax;
        this.email = email;
        this.proid = proid;
        this.comments = comments;
        this.opTime = opTime;
        this.opPerson = opPerson;
        this.orgStatus = orgStatus;
        this.nationid = nationid;
        this.cityid = cityid;
        this.parentId = parentId;
        this.bankaccount = bankaccount;
        this.vbrk = vbrk;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    public String getOrgSname() {
        return this.orgSname;
    }
    
    public void setOrgSname(String orgSname) {
        this.orgSname = orgSname;
    }

    public String getOrgFname() {
        return this.orgFname;
    }
    
    public void setOrgFname(String orgFname) {
        this.orgFname = orgFname;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getProid() {
        return this.proid;
    }
    
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    public Date getOpTime() {
        return this.opTime;
    }
    
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    public String getOpPerson() {
        return this.opPerson;
    }
    
    public void setOpPerson(String opPerson) {
        this.opPerson = opPerson;
    }

    public Integer getOrgStatus() {
        return this.orgStatus;
    }
    
    public void setOrgStatus(Integer orgStatus) {
        this.orgStatus = orgStatus;
    }

    public Integer getNationid() {
        return this.nationid;
    }
    
    public void setNationid(Integer nationid) {
        this.nationid = nationid;
    }

    public Integer getCityid() {
        return this.cityid;
    }
    
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    public String getParentId() {
        return this.parentId;
    }
    
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

	public String getBankaccount() {
		return bankaccount;
	}

	public void setBankaccount(String bankaccount) {
		this.bankaccount = bankaccount;
	}

	public String getVbrk() {
		return vbrk;
	}

	public void setVbrk(String vbrk) {
		this.vbrk = vbrk;
	}
   
}