package com.sinosoft.gypsymoth.pojo;

/**
 * AbstractOrganizationPort generated by MyEclipse Persistence Tools
 */

public abstract class AbstractOrganizationPort implements java.io.Serializable {

	// Fields

	private Integer id;
	private String orgId;
	private String portId;

	// Constructors

	/** default constructor */
	public AbstractOrganizationPort() {
	}

	/** full constructor */
	public AbstractOrganizationPort(String orgId, String portId) {
		this.orgId = orgId;
		this.portId = portId;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOrgId() {
		return this.orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public String getPortId() {
		return this.portId;
	}

	public void setPortId(String portId) {
		this.portId = portId;
	}

}