package com.sinosoft.gypsymoth.pojo;

import java.util.Date;

/**
 * AbstractExamPort generated by MyEclipse Persistence Tools
 */

public abstract class AbstractExamPort implements java.io.Serializable {

	// Fields

	private long id;
	private String appId;
	private String portName;
	private long nationid;
	private Date stopTime;
	private long stopStatus;

	// Constructors

	/** default constructor */
	public AbstractExamPort() {
	}

	/** full constructor */
	public AbstractExamPort(String appId, String portName, long nationid,
			Date stopTime, long stopStatus) {
		this.appId = appId;
		this.portName = portName;
		this.nationid = nationid;
		this.stopTime = stopTime;
		this.stopStatus = stopStatus;
	}

	// Property accessors

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getAppId() {
		return this.appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	public String getPortName() {
		return this.portName;
	}

	public void setPortName(String portName) {
		this.portName = portName;
	}

	public long getNationid() {
		return this.nationid;
	}

	public void setNationid(long nationid) {
		this.nationid = nationid;
	}

	public Date getStopTime() {
		return this.stopTime;
	}

	public void setStopTime(Date stopTime) {
		this.stopTime = stopTime;
	}

	public long getStopStatus() {
		return this.stopStatus;
	}

	public void setStopStatus(long stopStatus) {
		this.stopStatus = stopStatus;
	}

}