package com.sinosoft.gypsymoth.pojo;

import java.util.Date;


/**
 * AbstractOrganization generated by MyEclipse Persistence Tools
 */

public abstract class AbstractOrganization  implements java.io.Serializable {


    // Fields    

     private String id;
     private String orgSname;
     private String orgFname;
     private String address;
     private String contact;
     private String tel;
     private String fax;
     private String email;
     private Integer orgStatus;
     private String comments;
     private Date insTime;
     private Date upTime;
     private Date cancelTime;
     private Integer nationid;
     private Integer proid;
     private Integer cityid;
     private String parentId;
     private String orgId;
     private String bankaccount;
     private String vbrk;


    // Constructors

    /** default constructor */
    public AbstractOrganization() {
    }

	/** minimal constructor */
    public AbstractOrganization(Integer orgStatus, Date insTime, String orgId) {
        this.orgStatus = orgStatus;
        this.insTime = insTime;
        this.orgId = orgId;
    }
    
    /** full constructor */
    public AbstractOrganization(String orgSname, String orgFname, String address, String contact, String tel, String fax, String email, Integer orgStatus, String comments, Date insTime, Date upTime, Date cancelTime, Integer nationid, Integer proid, Integer cityid, String parentId, String orgId,String bankaccount,String vbrk) {
        this.orgSname = orgSname;
        this.orgFname = orgFname;
        this.address = address;
        this.contact = contact;
        this.tel = tel;
        this.fax = fax;
        this.email = email;
        this.orgStatus = orgStatus;
        this.comments = comments;
        this.insTime = insTime;
        this.upTime = upTime;
        this.cancelTime = cancelTime;
        this.nationid = nationid;
        this.proid = proid;
        this.cityid = cityid;
        this.parentId = parentId;
        this.orgId = orgId;
        this.bankaccount=bankaccount;
        this.vbrk=vbrk;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getOrgSname() {
        return this.orgSname;
    }
    
    public void setOrgSname(String orgSname) {
        this.orgSname = orgSname;
    }

    public String getOrgFname() {
        return this.orgFname;
    }
    
    public void setOrgFname(String orgFname) {
        this.orgFname = orgFname;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getOrgStatus() {
        return this.orgStatus;
    }
    
    public void setOrgStatus(Integer orgStatus) {
        this.orgStatus = orgStatus;
    }

    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    public Date getInsTime() {
        return this.insTime;
    }
    
    public void setInsTime(Date insTime) {
        this.insTime = insTime;
    }

    public Date getUpTime() {
        return this.upTime;
    }
    
    public void setUpTime(Date upTime) {
        this.upTime = upTime;
    }

    public Date getCancelTime() {
        return this.cancelTime;
    }
    
    public void setCancelTime(Date cancelTime) {
        this.cancelTime = cancelTime;
    }

    public Integer getNationid() {
        return this.nationid;
    }
    
    public void setNationid(Integer nationid) {
        this.nationid = nationid;
    }

    public Integer getProid() {
        return this.proid;
    }
    
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    public Integer getCityid() {
        return this.cityid;
    }
    
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    public String getParentId() {
        return this.parentId;
    }
    
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

	public String getBankaccount() {
		return bankaccount;
	}

	public void setBankaccount(String bankaccount) {
		this.bankaccount = bankaccount;
	}

	public String getVbrk() {
		return vbrk;
	}

	public void setVbrk(String vbrk) {
		this.vbrk = vbrk;
	}
   
}