package com.sinosoft.gypsymoth.pojo;



/**
 * AbstractOrganizationLevel generated by MyEclipse Persistence Tools
 */

public abstract class AbstractOrganizationLevel  implements java.io.Serializable {


    // Fields    

     private String id;
     private String parentId;
     private String isChild;
     private String orgName;
     private Integer orgStatus;
     private String orgUrl;
     private String personUrl;
     private Integer stampid;


    // Constructors

    /** default constructor */
    public AbstractOrganizationLevel() {
    }

	/** minimal constructor */
    public AbstractOrganizationLevel(String parentId, String isChild, String orgName, Integer orgStatus) {
        this.parentId = parentId;
        this.isChild = isChild;
        this.orgName = orgName;
        this.orgStatus = orgStatus;
    }
    
    /** full constructor */
    public AbstractOrganizationLevel(String parentId, String isChild, String orgName, Integer orgStatus, String orgUrl, String personUrl, Integer stampid) {
        this.parentId = parentId;
        this.isChild = isChild;
        this.orgName = orgName;
        this.orgStatus = orgStatus;
        this.orgUrl = orgUrl;
        this.personUrl = personUrl;
        this.stampid = stampid;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getParentId() {
        return this.parentId;
    }
    
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getIsChild() {
        return this.isChild;
    }
    
    public void setIsChild(String isChild) {
        this.isChild = isChild;
    }

    public String getOrgName() {
        return this.orgName;
    }
    
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public Integer getOrgStatus() {
        return this.orgStatus;
    }
    
    public void setOrgStatus(Integer orgStatus) {
        this.orgStatus = orgStatus;
    }

    public String getOrgUrl() {
        return this.orgUrl;
    }
    
    public void setOrgUrl(String orgUrl) {
        this.orgUrl = orgUrl;
    }

    public String getPersonUrl() {
        return this.personUrl;
    }
    
    public void setPersonUrl(String personUrl) {
        this.personUrl = personUrl;
    }

    public Integer getStampid() {
        return this.stampid;
    }
    
    public void setStampid(Integer stampid) {
        this.stampid = stampid;
    }
   








}