package com.sinosoft.gypsymoth.pojo;

/**
 * AbstractNation generated by MyEclipse Persistence Tools
 */

public abstract class AbstractNation implements java.io.Serializable {

	// Fields

	private Integer nationId;
	private String nationName;
	private String nationEnName;
	private String nationCnName;

	// Constructors

	/** default constructor */
	public AbstractNation() {
	}

	/** full constructor */
	public AbstractNation(String nationName,String nationEnName,String nationCnName) {
		this.nationName = nationName;
		this.nationEnName = nationEnName;
		this.nationCnName = nationCnName;
	}

	// Property accessors

	public Integer getNationId() {
		return this.nationId;
	}

	public void setNationId(Integer nationId) {
		this.nationId = nationId;
	}

	public String getNationName() {
		return this.nationName;
	}

	public void setNationName(String nationName) {
		this.nationName = nationName;
	}

	public String getNationEnName() {
		return nationEnName;
	}

	public void setNationEnName(String nationEnName) {
		this.nationEnName = nationEnName;
	}

	public String getNationCnName() {
		return nationCnName;
	}

	public void setNationCnName(String nationCnName) {
		this.nationCnName = nationCnName;
	}

	
}