package com.sinosoft.gypsymoth.pojo;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractPromary generated by MyEclipse Persistence Tools
 */

public abstract class AbstractPromary  implements java.io.Serializable {


    // Fields    

     private long proid;
     private String proname;
     private String englishname;
     private Set cities = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractPromary() {
    }

	/** minimal constructor */
    public AbstractPromary(String proname) {
        this.proname = proname;
    }
    
    /** full constructor */
    public AbstractPromary(String proname, String englishname, Set cities) {
        this.proname = proname;
        this.englishname = englishname;
        this.cities = cities;
    }

   
    // Property accessors

    public long getProid() {
        return this.proid;
    }
    
    public void setProid(long proid) {
        this.proid = proid;
    }

    public String getProname() {
        return this.proname;
    }
    
    public void setProname(String proname) {
        this.proname = proname;
    }

    public String getEnglishname() {
        return this.englishname;
    }
    
    public void setEnglishname(String englishname) {
        this.englishname = englishname;
    }

    public Set getCities() {
        return this.cities;
    }
    
    public void setCities(Set cities) {
        this.cities = cities;
    }
   








}