package com.sinosoft.gypsymoth.pojo;

// Generated by MyEclipse Persistence Tools

/**
 * City generated by MyEclipse Persistence Tools
 */
public class City extends AbstractCity implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public City() {
	}

	/** minimal constructor */
	public City(Promary promary, long cityid) {
		super(promary, cityid);
	}

	/** full constructor */
	public City(Promary promary, long cityid, String englishcityname) {
		super(promary, cityid, englishcityname);
	}

}
