package com.sinosoft.gypsymoth.pojo;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * Examinelog generated by MyEclipse Persistence Tools
 */
public class Examinelog extends AbstractExaminelog implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public Examinelog() {
	}

	/** full constructor */
	public Examinelog(long businessid, String description, String operatorid,
			Date operatortime, long gypsymoth1, long gypsymoth2,
			long gypsymoth3, long gypsymoth4, long doubt, String certificate,
			String examrecord, String workphoto, String gypsymothphoto,String shipinfo,String stopportinfo,String orgId,String orgcode) {
		super(businessid, description, operatorid, operatortime, gypsymoth1,
				gypsymoth2, gypsymoth3, gypsymoth4, doubt, certificate,
				examrecord, workphoto, gypsymothphoto,shipinfo,stopportinfo,orgId,orgcode);
	}

}
