package com.sinosoft.gypsymoth.pojo;

// Generated by MyEclipse Persistence Tools

/**
 * Nation generated by MyEclipse Persistence Tools
 */
public class Nation extends AbstractNation implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Nation() {
	} 

	/** full constructor */
	public Nation(String nationName,String nationEnName,String nationCnName) {
		super(nationName,nationEnName,nationCnName);
	}

}
