package com.sinosoft.gypsymoth.pojo;
// default package
// Generated by MyEclipse Persistence Tools

import java.util.Date;


/**
 * OpLog generated by MyEclipse Persistence Tools
 */
public class OpLog extends AbstractOpLog implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public OpLog() {
    }

    
    /** full constructor */
    public OpLog(String recordId, String personId, String accountId, String name, String sex, Date birthday, String education, String position, Date passTime, String tel, String mobile, String fax, String email, Integer isCoordinator, Integer isAuthorized, Integer isInspector, String attachment, Date opTime, String opName, String comments, Integer training, String orgId, String personType,String spell) {
        super(recordId, personId, accountId, name, sex, birthday, education, position, passTime, tel, mobile, fax, email, isCoordinator, isAuthorized, isInspector, attachment, opTime, opName, comments, training, orgId, personType,spell);        
    }
   
}
