package com.sinosoft.gypsymoth.pojo;

// Generated by MyEclipse Persistence Tools

/**
 * OrganizationPort generated by MyEclipse Persistence Tools
 */
public class OrganizationPort extends AbstractOrganizationPort implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public OrganizationPort() {
	}

	/** full constructor */
	public OrganizationPort(String orgId, String portId) {
		super(orgId, portId);
	}

}
