package com.sinosoft.gypsymoth.pojo;
// Generated by MyEclipse Persistence Tools



/**
 * OrganizationLevel generated by MyEclipse Persistence Tools
 */
public class OrganizationLevel extends AbstractOrganizationLevel implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public OrganizationLevel() {
    }

	/** minimal constructor */
    public OrganizationLevel(String parentId, String isChild, String orgName, Integer orgStatus) {
        super(parentId, isChild, orgName, orgStatus);        
    }
    
    /** full constructor */
    public OrganizationLevel(String parentId, String isChild, String orgName, Integer orgStatus, String orgUrl, String personUrl, Integer stampid) {
        super(parentId, isChild, orgName, orgStatus, orgUrl, personUrl, stampid);        
    }
   
}
