package com.sinosoft.gypsymoth.pojo;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * Organization generated by MyEclipse Persistence Tools
 */
public class Organization extends AbstractOrganization implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public Organization() {
	}

	/** minimal constructor */
	public Organization(Integer orgStatus, Date insTime, String orgId) {
		super(orgStatus, insTime, orgId);
	}

	/** full constructor */
	public Organization(String orgSname, String orgFname, String address,
			String contact, String tel, String fax, String email,
			Integer orgStatus, String comments, Date insTime, Date upTime,
			Date cancelTime, Integer nationid, Integer proid, Integer cityid,
			String parentId, String orgId,String bankaccount,String vbrk) {
		super(orgSname, orgFname, address, contact, tel, fax, email, orgStatus,
				comments, insTime, upTime, cancelTime, nationid, proid, cityid,
				parentId, orgId,bankaccount,vbrk);
	}

}
