package com.sinosoft.gypsymoth.pojo;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * OrgLog generated by MyEclipse Persistence Tools
 */
public class OrgLog extends AbstractOrgLog implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public OrgLog() {
	}

	/** minimal constructor */
	public OrgLog(String orgId, String orgSname, String orgFname,
			String address, String contact, String tel, String fax,
			String email, Date opTime, String opPerson, Integer orgStatus) {
		super(orgId, orgSname, orgFname, address, contact, tel, fax, email,
				opTime, opPerson, orgStatus);
	}

	/** full constructor */
	public OrgLog(String orgId, String orgSname, String orgFname,
			String address, String contact, String tel, String fax,
			String email, Integer proid, String comments, Date opTime,
			String opPerson, Integer orgStatus, Integer nationid, Integer cityid,
			String parentId,String bankaccount,String vbrk) {
		super(orgId, orgSname, orgFname, address, contact, tel, fax, email,
				proid, comments, opTime, opPerson, orgStatus, nationid, cityid,
				parentId,bankaccount,vbrk);
	}

}
