package com.sinosoft.gypsymoth.pojo;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * Person generated by MyEclipse Persistence Tools
 */
public class Person extends AbstractPerson implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Person() {
	}
//
//	/** minimal constructor */
//	public Person(String personId, String name, Integer id, String orgName,
//			String position, Integer training, Date passTime,
//			Integer isCoordinator, Integer isAuthorized, Integer isInspector) {
//		super(personId, name, id, orgName, position, training, passTime,
//				isCoordinator, isAuthorized, isInspector);
//	}

	/** full constructor */
	// select new
	// Person(p.personId,p.name,p.sex,p.birthday,p.education,p.position,p.training,p.passTime,p.tel,p.mobile,p.fax,p.email,ol.orgName,p.isCoordinator,p.isAuthorized,p.isInspector,p.attachment,ol.orgName)
	// from Person p,OrganizationLevel ol where p.orgId = ol.orgId and
	// p.personId=? order by p.personId desc
	// public Person(String personId, String name, String sex,
	// Date birthday, String education, String position, Integer training,
	// Date passTime, String tel, String mobile, String fax, String email,
	// Integer isCoordinator, Integer isAuthorized, Integer isInspector,
	// String attachment, String orgName) {
	// super(personId, name, sex, birthday, education, position,
	// training, passTime, tel, mobile, fax, email, isCoordinator,
	// isAuthorized, isInspector, attachment, orgName);
	// }
}
