package com.sinosoft.gypsymoth.pojo;

// Generated by MyEclipse Persistence Tools

/**
 * Port generated by MyEclipse Persistence Tools
 */
public class Port extends AbstractPort implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Port() {
	}

	/** minimal constructor */
	public Port(String portId, String portName, String portSname) {
		super(portId, portName, portSname);
	}

	/** full constructor */
	public Port(String portId, String portName, String portSname, Integer proid,
			Integer cityid) {
		super(portId, portName, portSname, proid, cityid);
	}

}
