package com.sinosoft.gypsymoth.pojo;

// Generated by MyEclipse Persistence Tools

/**
 * ProCityPort generated by MyEclipse Persistence Tools
 */
public class ProCityPort extends AbstractProCityPort implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public ProCityPort() {
	}

	/** minimal constructor */
	public ProCityPort(Integer proid, Integer cityid, Integer portid) {
		super(proid, cityid, portid);
	}

	/** full constructor */
	public ProCityPort(Integer proid, Integer cityid, Integer portid, String cityportid) {
		super(proid, cityid, portid, cityportid);
	}

}
