package com.sinosoft.gypsymoth.pojo;

// Generated by MyEclipse Persistence Tools

import java.util.Set;

/**
 * Promary generated by MyEclipse Persistence Tools
 */
public class Promary extends AbstractPromary implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Promary() {
	}

	/** minimal constructor */
	public Promary(String proname) {
		super(proname);
	}

	/** full constructor */
	public Promary(String proname, String englishname, Set cities) {
		super(proname, englishname, cities);
	}

}
